-- Переключаемся на базу данных User27
USE User27;
GO

-- Вставляем данные в таблицу ProductTypes из Product_type_import.xlsx
INSERT INTO ProductTypes (ProductTypeName, Coefficient)
VALUES
('Гостиные', 3.5),
('Прихожие', 5.6),
('Мягкая мебель', 3.0),
('Кровати', 4.7),
('Шкафы', 1.5),
('Комоды', 2.3);
GO

-- Вставляем данные в таблицу Materials из Material_type_import.xlsx
INSERT INTO Materials (MaterialName, LossPercentage)
VALUES
('Мебельный щит из массива дерева', 0.80),
('Ламинированное ДСП', 0.70),
('Фанера', 0.55),
('МДФ', 0.30);
GO

-- Вставляем данные в таблицу Workshops из Workshops_import.xlsx
INSERT INTO Workshops (WorkshopName, WorkshopType, StaffCount)
VALUES
('Проектный', 'Проектирование', 4),
('Расчетный', 'Проектирование', 5),
('Раскроя', 'Обработка', 5),
('Обработки', 'Обработка', 6),
('Сушильный', 'Сушка', 3),
('Покраски', 'Обработка', 5),
('Столярный', 'Обработка', 7),
('Изготовления изделий из искусственного камня и композитных материалов', 'Обработка', 3),
('Изготовления мягкой мебели', 'Обработка', 5),
('Монтажа стеклянных, зеркальных вставок и других изделий', 'Сборка', 2),
('Сборки', 'Сборка', 6),
('Упаковки', 'Сборка', 4);
GO

-- Вставляем данные в таблицу Products из Products_import.xlsx
INSERT INTO Products (Article, ProductTypeID, ProductName, MinPartnerCost, MainMaterialID)
VALUES
('1549922', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Гостиные'), 'Комплект мебели для гостиной Ольха горная', 160507.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('1018556', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Гостиные'), 'Стенка для гостиной Вишня темная', 216907.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('3028272', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Прихожие'), 'Прихожая Венге Винтаж', 24970.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Ламинированное ДСП')),
('3029272', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Прихожие'), 'Тумба с вешалкой Дуб натуральный', 18206.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Ламинированное ДСП')),
('3028248', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Прихожие'), 'Прихожая-комплект Дуб темный', 177509.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('7118827', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Мягкая мебель'), 'Диван-кровать угловой Книжка', 85900.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('7137981', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Мягкая мебель'), 'Диван модульный Телескоп', 75900.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('7029787', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Мягкая мебель'), 'Диван-кровать Соло', 120345.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('7758953', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Мягкая мебель'), 'Детский диван Выкатной', 25990.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Фанера')),
('6026662', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Кровати'), 'Кровать с подъемным механизмом с матрасом 1600х2000 Венге', 69500.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('6159043', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Кровати'), 'Кровать с матрасом 90х2000 Венге', 55600.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Ламинированное ДСП')),
('6588376', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Кровати'), 'Кровать универсальная Дуб натуральный', 37900.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Ламинированное ДСП')),
('6758375', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Кровати'), 'Кровать с ящиками Ясень белый', 46750.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Фанера')),
('2759324', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Шкафы'), 'Шкаф-купе 3-х дверный Сосна белая', 131560.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Ламинированное ДСП')),
('2118827', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Шкафы'), 'Стеллаж Бук натуральный', 38700.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('2559898', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Шкафы'), 'Шкаф 4 дверный с ящиками Ясень серый', 160151.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Фанера')),
('2259474', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Шкафы'), 'Шкаф-пенал Береза белый', 40500.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Фанера')),
('4115947', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Комоды'), 'Комод 6 ящиков Вишня светлая', 61235.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('4033136', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Комоды'), 'Комод 4 ящика Вишня светлая', 41200.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'Мебельный щит из массива дерева')),
('4028048', (SELECT ProductTypeID FROM ProductTypes WHERE ProductTypeName = 'Комоды'), 'Тумба под ТВ', 12350.00, (SELECT MaterialID FROM Materials WHERE MaterialName = 'МДФ'));
GO

-- Вставляем данные в таблицу ProductWorkshops из Product_workshops_import.xlsx
INSERT INTO ProductWorkshops (ProductID, WorkshopID, ManufacturingTime)
VALUES
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с подъемным механизмом с матрасом 1600х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Изготовления изделий из искусственного камня и композитных материалов'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Изготовления изделий из искусственного камня и композитных материалов'), 2.7),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать угловой Книжка'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Изготовления мягкой мебели'), 4.2),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Изготовления мягкой мебели'), 4.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Изготовления мягкой мебели'), 4.7),
((SELECT ProductID FROM Products WHERE ProductName = 'Детский диван Выкатной'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Изготовления мягкой мебели'), 4.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с матрасом 90х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Изготовления мягкой мебели'), 5.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Монтажа стеклянных, зеркальных вставок и других изделий'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая Венге Винтаж'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Монтажа стеклянных, зеркальных вставок и других изделий'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Монтажа стеклянных, зеркальных вставок и других изделий'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с подъемным механизмом с матрасом 1600х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Монтажа стеклянных, зеркальных вставок и других изделий'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-купе 3-х дверный Сосна белая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Монтажа стеклянных, зеркальных вставок и других изделий'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Монтажа стеклянных, зеркальных вставок и других изделий'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая Венге Винтаж'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба с вешалкой Дуб натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать угловой Книжка'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Детский диван Выкатной'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с подъемным механизмом с матрасом 1600х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.6),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с матрасом 90х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать универсальная Дуб натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.8),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с ящиками Ясень белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-купе 3-х дверный Сосна белая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф 4 дверный с ящиками Ясень серый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 1.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-пенал Береза белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 6 ящиков Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 4 ящика Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.4),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Обработки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.4),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать угловой Книжка'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Детский диван Выкатной'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с подъемным механизмом с матрасом 1600х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.4),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с ящиками Ясень белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 1.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-пенал Береза белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 2.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 6 ящиков Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 4 ящика Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.4),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Покраски'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Проектный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Проектный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Проектный'), 1.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Проектный'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-купе 3-х дверный Сосна белая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Проектный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Проектный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Проектный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая Венге Винтаж'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба с вешалкой Дуб натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать угловой Книжка'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Детский диван Выкатной'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 0.7),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с подъемным механизмом с матрасом 1600х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с матрасом 90х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать универсальная Дуб натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.1),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с ящиками Ясень белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-купе 3-х дверный Сосна белая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф 4 дверный с ящиками Ясень серый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-пенал Береза белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 6 ящиков Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 4 ящика Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Раскроя'), 0.6),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Расчетный'), 0.4),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Расчетный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Расчетный'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Расчетный'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-купе 3-х дверный Сосна белая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Расчетный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Расчетный'), 0.7),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Расчетный'), 0.4),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая Венге Винтаж'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать угловой Книжка'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать универсальная Дуб натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 0.8),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с ящиками Ясень белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-купе 3-х дверный Сосна белая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 1.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф 4 дверный с ящиками Ясень серый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 6 ящиков Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сборки'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 1.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Детский диван Выкатной'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф 4 дверный с ящиками Ясень серый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 1.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-пенал Береза белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 3.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 6 ящиков Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 4 ящика Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Столярный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стенка для гостиной Вишня темная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать угловой Книжка'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 6 ящиков Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 4 ящика Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Сушильный'), 2.0),
((SELECT ProductID FROM Products WHERE ProductName = 'Комплект мебели для гостиной Ольха горная'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба с вешалкой Дуб натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Прихожая-комплект Дуб темный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.2),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать угловой Книжка'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван модульный Телескоп'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.2),
((SELECT ProductID FROM Products WHERE ProductName = 'Диван-кровать Соло'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Детский диван Выкатной'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с подъемным механизмом с матрасом 1600х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с матрасом 90х2000 Венге'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать универсальная Дуб натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.3),
((SELECT ProductID FROM Products WHERE ProductName = 'Кровать с ящиками Ясень белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.2),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-купе 3-х дверный Сосна белая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Стеллаж Бук натуральный'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.2),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф 4 дверный с ящиками Ясень серый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Шкаф-пенал Береза белый'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.5),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 6 ящиков Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.2),
((SELECT ProductID FROM Products WHERE ProductName = 'Комод 4 ящика Вишня светлая'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.2),
((SELECT ProductID FROM Products WHERE ProductName = 'Тумба под ТВ'), (SELECT WorkshopID FROM Workshops WHERE WorkshopName = 'Упаковки'), 0.3);
GO